// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CampaignByID(ctx context.Context, id int32) (*CampaignByIDRow, error)
	CreateCampaign(ctx context.Context, arg *CreateCampaignParams) (int32, error)
	DeleteCampaign(ctx context.Context, id int32) error
	Donate(ctx context.Context, arg *DonateParams) error
	DonationsByUserID(ctx context.Context, userID pgtype.Int4) ([]*DonationsByUserIDRow, error)
}

var _ Querier = (*Queries)(nil)
